meta_product_name: "TasksLists"
meta_title: "TasksLists ---  Stay Up-To-Date and Organized"
meta_description: "Keep track of all the tasks you have to do and see which ones you already finished."
meta_image: "logo.png" # should exist in `app/assets/images/`
